---
# Setup the user for hadoop

- name: Create hadoop user who will own everythinhg
  user: 
    name: "{{ hadoop_user }}"

##---- HDFS user setup ----------------------------------##
- name: Creat hdfs user with key on master
  user: 
    name: "{{ hdfs_user }}" 
    generate_ssh_key: yes
    ssh_key_bits: 2048 
    ssh_key_file: ".ssh/id_rsa"
    groups: "{{ hadoop_group }}"
    append: yes
  when: inventory_hostname == 'hadoop-namenode-1'

- name: Load hdfs users public key from master
  command: cat /home/{{ hdfs_user }}/.ssh/id_rsa.pub
  register: pub_key
  when: inventory_hostname == 'hadoop-namenode-1'

- name: Create hdfs user on workers
  user: 
    name: "{{ hdfs_user }}"
    groups: "{{ hadoop_group }}"
    append: yes
  with_items:
    - "{{ groups['hadoop-nodes'] }}"

- name: Add authorized key to all hadoop nodes
  authorized_key: 
    user: "{{ hdfs_user }}"
    key: "{{ hostvars['hadoop-namenode-1']['pub_key']['stdout'] }}"

- name: Disable strict host key checking
  template:
    src: "templates/ssh_config"
    dest: "/home/{{ hdfs_user }}/.ssh/config"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_user }}"