#!/bin/bash
# chkconfig: 2345 80 20
# description: HDFS services \
#source /etc/xpatterns/xpatterns.ini
USER={{ hdfs_user }}
NAME=hdfs
DESC="hdfs"
HADOOP_HOME={{ hadoop_home }}
DAEMON=sbin/start-dfs.sh
STOP_DAEMON=sbin/stop-dfs.sh
START_LOG=hadoop_start.log
STOP_LOG=hadoop_stop.log

#Helper functions
start() {
        su - $USER -c "cd $HADOOP_HOME; $DAEMON" > $START_LOG 2>&1 < /dev/null &
        sleep 3
}

stop() {
        su - $USER -c "cd $HADOOP_HOME; $STOP_DAEMON" > $STOP_LOG 2>&1 < /dev/null &
        sleep 5
        pid_master=$(ps aux | grep org.apache.hadoop.hdfs.server | grep -v grep | awk '{print $2}')
        if [ -z "$pid_master" ]; then
                echo "NameNode stopped"
        else
                echo "kill NameNode pid $pid_master"
                kill -15 $pid_master
        fi
        pid_slave=$(ps aux | grep org.apache.hadoop.hdfs.server.datanode | grep -v grep | awk '{print $2}')
        if [ -z "$pid_slave" ]; then
                echo "Datanode stopped"
        else
                echo "kill Datanode pid $pid_slave"
                kill -15 $pid_slave
        fi
}

status() {
        pid_master=$(ps aux | grep org.apache.hadoop.hdfs.server | grep -v grep | awk '{print $2}')
        if [ -z "$pid_master" ]; then
                echo "NameNode stopped"
        else
                echo "NameNode is running pid $pid_master"
        fi
        echo -n "SALVES:"
        for slave in $(cat $HADOOP_HOME/etc/hadoop/slaves | grep -v "#"); do
            slave_pid=$(su - $USER -c "ssh $USER@$slave ps aux | grep org.apache.hadoop.hdfs.server.datanode | grep -v grep" | awk '{print $2}')
            if [ -z "$slave_pid" ]; then
                echo "Datanode on $slave stopped"
            else
                echo "Datanode started on $slave - pid $slave_pid"
            fi

        done
}

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start
        echo "$NAME started."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        stop
        echo "$NAME stopped."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        #set +e
        stop
        #set -e
        sleep 5
        start

        echo "$NAME restarted."
        ;;
  status)
        echo -n "Status of NameNode: "
        status
	;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0


